version: '2.3'

services:
    webserver:
        container_name: webserver
        build:
            context: ./bin/webserver
        restart: 'always'
        ports:
            - 9090:80
            - 8000:8000
        links:
            - mysql
        volumes:
            - /home/:/home/
            - ./api/:/var/www/api/
            - ./compose-data/react/:/var/www/html/
            - ./config/php/php.ini:/usr/local/etc/php/php.ini
            - ./config/vhosts:/etc/apache2/sites-enabled
            - ./compose-data/logs/apache2:/var/log/apache2

    mysql:
        container_name: mysql
        image: mysql:5.7
        restart: 'always'
        volumes:
            - ./compose-data/data/mysql:/var/lib/mysql
            - ./compose-data/logs/mysql:/var/log/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=docker
            - MYSQL_DATABASE=docker
            - MYSQL_USER=docker
            - MYSQL_PASSWORD=docker
        logging:
            driver: none

    react-webui:
        container_name: react-webui
        build:
            context: ./react_app
            dockerfile: Dockerfile
        volumes:
            - "./compose-data/react/:/build/"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: 'phpmyadmin'
        links:
            - mysql
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
            - PMA_USER=docker
            - PMA_PASSWORD=docker
            - MYSQL_ROOT_PASSWORD=docker
            - MYSQL_USER=docker
            - MYSQL_PASSWORD=docker
        ports:
            - "8080:80"
        volumes:
            - /sessions
        logging:
            driver: none

    #composer:
    # restart: 'no'
    #  image: composer/composer:php7
    #  command: install
    #  volumes:
    #    - .:/app
