version: "3"

services:
    webserver:
        build:
            context: ./bin/webserver
        container_name: '7.3.x-webserver'
        restart: 'always'
        ports:
            - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
        links:
            - mysql
        volumes:
            - ${DOCUMENT_ROOT-./www}:/var/www/html
            - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
            - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
            - ./compose-data/logs/apache2}:/var/log/apache2
    mysql:
        image: mysql:5.7
        restart: 'always'
        #ports:
        #- "${HOST_MACHINE_MYSQL_PORT}:3306"
        volumes:
            - ./compose-data/data/mysql:/var/lib/mysql
            - ./compose-data/logs/mysql:/var/log/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: 'sc-phpmyadmin'
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: ${MYSQL_USER}
            PMA_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - '8080:80'
        volumes:
            - /sessions
